name: first workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: windows-latest
    steps: 
      - name: print greeting
        run: echo "heloo fucker"
      - name: print goodbye
        run: echo"byebye bitch"
